# JVM args for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Android
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin
kotlin.code.style=official

# Optimisations
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configureondemand=false

# Autorise compileSdk 36 (Android 16) avec AGP 8.4.2 (exigence Google Play).
android.suppressUnsupportedCompileSdk=36
